# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nazouz <nazouz@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/05/10 14:18:14 by nazouz            #+#    #+#              #
#    Updated: 2024/05/10 14:21:32 by nazouz           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME			=			megaphone

CPP				=			c++

CPPFLAGS		=			-Wall -Wextra -Werror

SRCS			=			./megaphone.cpp


all : $(NAME)

$(NAME) :
	$(CPP) $(CPPFLAGS) $(SRCS) -o $(NAME)

fclean :
	rm -rf 